name: ShellCheck Linting

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs ShellCheck to lint shell scripts
    - uses: ludeeus/action-shellcheck@0.1.0  # Check for the latest or more stable version
